services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: saltedlolly-cloudflare-ddns_ui_1
      APP_PORT: 3000
      # Disable SSO for local testing
      PROXY_AUTH_ADD: "false"

  ui:
    image: saltedlolly/cloudflare-ddns-ui@sha256:c467a8c667feafd5e6d560d754453cce895d1d01ad440bf4eebee5531bf3d1f0
    container_name: saltedlolly-cloudflare-ddns_ui_1
    hostname: saltedlolly-cloudflare-ddns_ui_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cloudflare-ddns:
    image: saltedlolly/cloudflare-ddns@sha256:80803d508852ce62290ef11daaa6d8dc74784f528a0968435e997f1094628bf7
    container_name: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    hostname: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /data/status.json && grep -q '\"status\": \"running\"' /data/status.json || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 6
    depends_on:
      - ui

volumes:
  cloudflare-ddns-data:
