services:
  ui:
    image: saltedlolly/cloudflare-ddns-ui@sha256:7b050c38cb49c4ce9e04e25cc4b74780c5e4100d629645f820c5b9082a1b4486
    container_name: saltedlolly-cloudflare-ddns_ui_1
    hostname: saltedlolly-cloudflare-ddns_ui_1
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cloudflare-ddns:
    image: saltedlolly/cloudflare-ddns@sha256:eab3c8eb82929dcf58fa25177b3a9e9fe405177b48a5a230b2047b6b339c0389
    container_name: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    hostname: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /data/status.json && grep -q '\"status\": \"running\"' /data/status.json || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 6
    depends_on:
      - ui

volumes:
  cloudflare-ddns-data:
