services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: saltedlolly-cloudflare-ddns_ui_1
      APP_PORT: 3000
      # Disable SSO for local testing
      PROXY_AUTH_ADD: "false"

  ui:
    image: saltedlolly/cloudflare-ddns-ui@sha256:6e448d539e8b80dcb845fbb5db8e15ef1eb4bf445ef04d0738ffe8a598d44ebf
    container_name: saltedlolly-cloudflare-ddns_ui_1
    hostname: saltedlolly-cloudflare-ddns_ui_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cloudflare-ddns:
    image: saltedlolly/cloudflare-ddns@sha256:e64373c7770eace012b2996894eec411f8a966acdd66f265722370603e66054a
    container_name: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    hostname: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /data/status.json && grep -q '\"status\": \"running\"' /data/status.json || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 6
    depends_on:
      - ui

volumes:
  cloudflare-ddns-data:
