services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: saltedlolly-cloudflare-ddns_ui_1
      APP_PORT: 3000

  ui:
    image: saltedlolly/cloudflare-ddns-ui@sha256:dd08a6fec8eb754ab5046c44daf469e1b03ab44e2392dcba5b5b55f52efe0724
    container_name: saltedlolly-cloudflare-ddns_ui_1
    hostname: saltedlolly-cloudflare-ddns_ui_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
      - NODE_ENV=production
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cloudflare-ddns:
    image: saltedlolly/cloudflare-ddns@sha256:2b3c564304a4e2e27c165f67e354f35c093e22af0458c06c19b93626602e7858
    container_name: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    hostname: saltedlolly-cloudflare-ddns_cloudflare-ddns_1
    init: true
    restart: unless-stopped
    environment:
      - APP_DATA_DIR=/data
    volumes:
      - cloudflare-ddns-data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /data/status.json && grep -q '\"status\": \"running\"' /data/status.json || exit 1"]
      interval: 1m
      timeout: 20s
      retries: 6
    depends_on:
      - ui

volumes:
  cloudflare-ddns-data:
